#
#spring.datasource.url=jdbc:postgresql://localhost:5432/for_portfolio
#spring.datasource.username=postgres
#spring.datasource.password=root
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL92Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

#upload:
#    server:
#        folder: D:\\Server

#spring.servlet.multipart.location=D:/Server

server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/for_portfolio
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
upload:
  server:
    folder: D:\Server



